-- Add profile fields and instructor role to TRAINEES
ALTER TABLE TRAINEES ADD COLUMN Specialty VARCHAR(100) DEFAULT NULL;
ALTER TABLE TRAINEES ADD COLUMN PriorSimulationExperience VARCHAR(50) DEFAULT NULL;
ALTER TABLE TRAINEES ADD COLUMN Role VARCHAR(20) DEFAULT 'trainee';
